apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: hello
  labels:
    app.kubernetes.io/name: hello-node
spec:
  selector:
    app.kubernetes.io/name: hello-node
  ports:
    - name: http
      port: 80
      targetPort: http

